DEFAULT_NUM_INFERENCE_STEPS = 50
DEFAULT_TIMEOUT = 15

DEFAULT_RABBIT_PORT = 8093
DEFAULT_ENDPOINT_PORT = 8094
DEFAULT_IMAGE_SCORER_PORT = 8089
DEFAULT_AXON_IP = "127.0.0.1"
DEFAULT_AXON_PORT = 9090

RABBIT_ADDRESS = "127.0.0.1:" + str(DEFAULT_RABBIT_PORT)
IMAGE_SCORER_ADDRESS = "127.0.0.1:" + str(DEFAULT_IMAGE_SCORER_PORT)

# auth values
DEFAULT_MINIMUM_WTAO_BALANCE = 0
NEEDS_AUTHENTICATION = True
NEEDS_METAMASK_VERIFICATION = False
SAVE_IMAGES = False